services:
  postgresdb:
    image: postgres:17
    container_name: auth_with_ts_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_with_TS
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
